# Using Apply On A DataFrame

## Notebook Outline:
* [Introduction to .apply()](#introtoapply)
* [An example on our baby boy name data](#examplebabyname)
* [Another example on our labor sheet data](#examplelaborsheet)

# Google Colab Path Note

If you run this notebook in Google Colab, mount Google Drive first:

```python
from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = '/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis'
DATA_DIR = f'{BASE_DIR}/05_Datasets'
ASSIGNMENTS_DIR = f'{BASE_DIR}/04_Assignments'
OUTPUTS_DIR = f'{BASE_DIR}/04_Assignments/Outputs'
```

If you run locally in Jupyter/Anaconda, do not use `/content/drive`; use relative paths such as `../05_Datasets/...`.
The Mac path `/Users/yuzhang/.../My Drive/...` is only for local file browsing and is not a Colab path.

<a name=introtoapply></a>
# Introduction to .apply()

The .apply() method we are going to learn about is exactly like the .apply() we learned about int our groupby lectures.  The only difference is that this the method for dataframes instead of groupby objects.

The docs are here: <https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html>

We are going to go back to our baby boy name data for our first example. So, let's load the data!

<a name=examplebabyname></a>
# An example of using .apply() on our baby boy name data:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

filepath = ('/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis/05_Datasets/Most_Popular_Baby_Boy_Names__Illinois_1980-2013.csv')
nameData = pd.read_csv(filepath)

#### Let's take a look at these name values again - we will use .unique() to do so:

In [ ]:
nameData['Name'].unique()

array(['Michael', 'Jason', 'Christopher', 'Matthew', 'David', 'James',
       'Robert', 'Daniel', 'John', 'Joseph', 'Brian', 'Joshua', 'Ryan',
       'Nicholas', 'Eric', 'Justin', 'Timothy', 'William', 'Anthony',
       'Andrew', 'Adam', 'Thomas', 'Kevin', 'Steven', 'Jeremy',
       'Jonathan', 'Brandon', 'Kyle', 'Jospeh', 'Jonathon', 'Jacob',
       'Zachary', 'Alexander', 'Tyler', 'Austin', 'Dylan', 'Benjamin',
       'Ethan', 'Christian', 'Samuel', 'Zachery', 'Nathan', 'Jack',
       'DANIEL', 'JACOB', 'MICHAEL', 'ALEXANDER', 'JOSHUA', 'ANTHONY',
       'MATTHEW', 'JOSEPH', 'ETHAN', 'ANDREW', 'RYAN', 'CHRISTOPHER',
       'NICHOLAS', 'DAVID', 'WILLIAM', 'NATHAN', 'JOHN', 'BENJAMIN',
       'JAMES', 'TYLER', 'LOGAN', 'JACK', 'NOAH', 'JONATHAN', 'ANGEL',
       'CHRISTIAN', 'JAYDEN', 'AIDEN', 'JACKSON', 'MASON', 'LUCAS',
       'LIAM', 'GABRIEL', 'ELIJAH', 'HENRY'], dtype=object)

#### Most likely, we don't want Michael and MICHAEL to count as two different names - let's fix that using .apply(), lambda, and .lower() to fix this problem!

The basic idea here is want to lower case all of the names, this way all the 'Michael's will be changed to 'michael' and the 'MICHAEL's will be changed to 'michael'. Now every Michael will be counted as the same name! We can lower case string using the .lower() method, let's review this below.

In [ ]:
name = 'MICHAEL'
print(name.lower())

# Note you can call .lower() directly on the string as well:
print('MICHAEL'.lower())

michael
michael

#### Now let's use .apply() to _apply_ the .lower() method to the all the names in the 'Names' column
We have to wrap it in a lamabda function though! We can only pass _functions_ to the apply() method, we can not pass other methods.

As a review, let's first write function that will convert a string to lower case.

In [ ]:
def lowerString(aString):
    lowerString = aString.lower()
    return lowerString

lowerString('MICHAEL')

'michael'

#### Let's now apply this function to the entire column of names

In [ ]:
nameData['Name'].apply(lowerString)

0          michael
1            jason
2      christopher
3          matthew
4            david
          ...
845         nathan
846         andrew
847          henry
848          david
849           jack
Name: Name, Length: 850, dtype: object

#### Now, let's do the same, but use a _lambda_ function instead!

In [ ]:
nameData['Name'].apply(lambda x: x.lower())

0          michael
1            jason
2      christopher
3          matthew
4            david
          ...
845         nathan
846         andrew
847          henry
848          david
849           jack
Name: Name, Length: 850, dtype: object

#### Now let's actually update the values in the dataset:

In [ ]:
nameData.loc[:, 'Name'] = nameData['Name'].apply(lambda x: x.lower())

#### Now we are free to groupby the names!

In [ ]:
nameData.groupby('Name')['Rank'].mean().sort_values().head(5)

Name
michael    1.705882
jacob      3.833333
daniel     4.441176
matthew    5.176471
liam       7.666667
Name: Rank, dtype: float64

<a name=examplelaborsheet></a>
# Another example of apply on our labor sheet data

In [ ]:
filepath = ('/content/drive/MyDrive/Colab Notebooks/UCI/UCI_427.62_Python_for_Data_Analysis/05_Datasets/M5_LaborSheetData.csv')
laborSheetData = pd.read_csv(filepath, parse_dates=[[2, 3], 13])
laborSheetData.head()

/tmp/ipykernel_2553/229845300.py:2: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  laborSheetData = pd.read_csv(filepath, parse_dates=[[2, 3], 13])
/tmp/ipykernel_2553/229845300.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  laborSheetData = pd.read_csv(filepath, parse_dates=[[2, 3], 13])

,Hour_Day_Part,Store,Business_Date,Transactions,Net_Sales,Labor_Hours,Drive_Thru_Avg_Seconds,Crew_Count,Manager,Weather,Promotion_Flag,Customer_Satisfaction,Timestamp
0,00:00 Breakfast,Training Store,2022-01-03,80,650.0,10.00,120,4,Sample Manager,Rain,True,4.00,2022-01-03 00:00:00
1,01:00 Breakfast,Training Store,2022-01-03,87,733.5,11.25,129,5,Sample Manager,Clear,False,4.15,2022-01-03 01:00:00
2,02:00 Breakfast,Training Store,2022-01-03,94,817.0,12.50,138,6,Sample Manager,Clear,False,4.30,2022-01-03 02:00:00
3,03:00 Breakfast,Training Store,2022-01-03,101,900.5,13.75,147,7,Sample Manager,Clear,False,4.45,2022-01-03 03:00:00
4,04:00 Breakfast,Training Store,2022-01-03,108,984.0,15.00,156,8,Sample Manager,Rain,False,4.60,2022-01-03 04:00:00

#### Let's calculate the difference between 'TimeStamp' and 'Date_Hour' using .apply() and lambda. Because we are applying the apply() to the whole dataframe, we have to specific the axis that we will be apply the function across - this is confusing, so said another way if you want to apply the function every column then axis will equal 0, if you want to apply the function to every row, axis will equal 1

In [ ]:
laborSheetData['Business_Date'] = pd.to_datetime(laborSheetData['Business_Date'])
laborSheetData['Date_Hour'] = pd.to_datetime(laborSheetData['Business_Date'].dt.strftime('%Y-%m-%d') + ' ' + laborSheetData['Hour_Day_Part'].str[:5])
laborSheetData['lateEnteringData'] = laborSheetData.apply(lambda x: x['Timestamp'] - x['Date_Hour'], axis=1)

In [ ]:
laborSheetData.head(3)

,Hour_Day_Part,Store,Business_Date,Transactions,Net_Sales,Labor_Hours,Drive_Thru_Avg_Seconds,Crew_Count,Manager,Weather,Promotion_Flag,Customer_Satisfaction,Timestamp,Date_Hour,lateEnteringData
0,00:00 Breakfast,Training Store,2022-01-03,80,650.0,10.00,120,4,Sample Manager,Rain,True,4.00,2022-01-03 00:00:00,2022-01-03 00:00:00,0 days
1,01:00 Breakfast,Training Store,2022-01-03,87,733.5,11.25,129,5,Sample Manager,Clear,False,4.15,2022-01-03 01:00:00,2022-01-03 01:00:00,0 days
2,02:00 Breakfast,Training Store,2022-01-03,94,817.0,12.50,138,6,Sample Manager,Clear,False,4.30,2022-01-03 02:00:00,2022-01-03 02:00:00,0 days


---

# Additional Students' Practice and Answer Key

These practice questions are designed for undergraduate students. Try the **Student Practice** cell first, then compare your work with the **Completed Answer** cell.

## Student Practice 1: Use Apply
Create a DataFrame with scores. Use `.apply()` to convert each score into a letter grade.

## Student Practice 2: Add Feedback
Use `.apply()` to add feedback: `Strong` for scores 85 or higher, otherwise `Keep practicing`.

In [ ]:
# Completed Answer: Apply Practice
import pandas as pd

df = pd.DataFrame({'student': ['A', 'B', 'C', 'D'], 'score': [95, 82, 74, 60]})

def letter_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'Needs improvement'

df['letter_grade'] = df['score'].apply(letter_grade)
df['feedback'] = df['score'].apply(lambda x: 'Strong' if x >= 85 else 'Keep practicing')

display(df)